export const ROLE_CODE = {
  HR_FOCAL_ADMIN: 'HR_FOCAL_ADMIN',
  CAPE_ADMIN: 'CAPE_ADMIN',
  INDIVIDUAL_LEARNER: 'INDIVIDUAL_LEARNER',
  HYBRID_LEARNER: 'HYBRID_LEARNER',
  CLASSROOM_LEARNER: 'CLASSROOM_LEARNER',
} as const;
