// shared/constants/error-item-codes.ts
export const EMAIL_NOT_FOUND_QUERY = 'EMAIL_NOT_FOUND_QUERY';
export const PASSWORD_FIELD_REQUIRED = 'PASSWORD_FIELD_REQUIRED';
export const ROLE_CODE_FIELD_REQUIRED = 'ROLE_CODE_FIELD_REQUIRED';
